# Generated by Django 5.0.6 on 2024-05-16 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tmsiti_app', '0004_rating'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together=set(),
        ),
    ]
